    {4*256+5, R"(
X11 font “micro”. For clarity, this font is pictured as 4x6 on this page
by inserting a blank pixel line below every character, but the font is
really 4x5. This means that capital letters on adjacent lines are touching.

Besides the full ASCII, this font includes an odd set of special characters,
including ẍ, some Greek symbols, logical operators, and the APL asterisk
with diearesis that I have never seen used anywhere, for a total of 128
glyphs.
)"},
    {4*256+6, "X11 misc-fixed font `-misc-fixed-medium-r-normal--6-60-75-75-c-40-iso10646-1`."},
    {5*256+7, "X11 misc-fixed font `-misc-fixed-medium-r-normal--7-70-75-75-c-50-iso10646-1`."},
    {5*256+8, "X11 misc-fixed font `-misc-fixed-medium-r-normal--8-80-75-75-c-50-iso10646-1`."},
    {6*256+9, "X11 misc-fixed font `-misc-fixed-medium-r-normal--9-90-75-75-c-60-iso10646-1`."},
    {6*256+10, "X11 misc-fixed font `-misc-fixed-medium-r-normal--10-100-75-75-c-60-iso10646-1`."},
    {6*256+12, R"(
* X11 misc-fixed font `-misc-fixed-medium-r-semicondensed--12-110-75-75-c-60-iso10646-1`.
* Uni2-Terminus12x6.psf.gz (Linux consolefonts)
)"},
    {6*256+13, "X11 misc-fixed font `-misc-fixed-bold-r-semicondensed--13-120-75-75-c-60-iso10646-1`. Pairs perfectly with 12x13."},
    {7*256+13, "X11 misc-fixed font `-misc-fixed-bold-r-normal--13-120-75-75-c-70-iso10646-1`."},
    {7*256+14, "X11 misc-fixed font `-misc-fixed-bold-r-normal--14-130-75-75-c-70-iso10646-1`."},
    {8*256+13, "X11 misc-fixed font `-misc-fixed-bold-r-normal--13-120-75-75-c-80-iso10646-1`."},
    {9*256+15, "X11 misc-fixed font `-misc-fixed-bold-r-normal--15-140-75-75-c-90-iso10646-1`."},
    {9*256+18, "X11 misc-fixed font `-misc-fixed-bold-r-normal--18-120-100-100-c-90-iso10646-1`. Pairs perfectly with 18x18."},
    {10*256+20, R"(
* X11 misc-fixed font `-misc-fixed-medium-r-normal--20-200-75-75-c-100-iso10646-1`.
* Uni2-TerminusBold20x10.psf.gz (Linux consolefonts)
)"},
    {12*256+13, "X11 misc-fixed font `-misc-fixed-medium-r-normal-ja-13-120-75-75-c-120-iso10646-1` (Japanese)."},
    {18*256+18, R"(
X11 misc-fixed fonts `-misc-fixed-medium-r-normal-ja-18-120-100-100-c-180-iso10646-1` (Japanese)
and `-misc-fixed-medium-r-normal-ko-18-120-100-100-c-180-iso10646-1` (Korean).

Like many other fonts in this emulator,
it merges two different source fonts
with identical dimensions into one.
)"},

    {8*256+19, "vga8x19.bdf by Martin Reuber, based on VGA ROM BIOS font"},

    {8*256+8, R"(
* VGA ROM BIOS font (codepage 437)
* DISPLAY.SYS codepage 850
* DISPLAY.SYS codepage 852
* iso01.f08.psf.gz, iso08.f08.psf.gz (Linux consolefonts)
* lat1-08.psf.gz, lat2-08.psf.gz (Linux consolefonts)
* Uni1-VGA8.psf.gz, Uni2-VGA8.psf.gz (Linux consolefonts)
)"},
    {8*256+10, R"(
* 8x10 Source unknown (possibly created automatically by resizing 8x12)
* lat1-10.psf.gz, lat2-10.psf.gz, lat4-10.psf.gz, lat9-10.psf.gz (Linux consolefonts)
)"},
    {8*256+12, R"(
* 8x12 Source unknown (possibly created automatically by resizing 8x14)
* lat1-10.psf.gz, lat2-10.psf.gz, lat4-10.psf.gz, lat9-10.psf.gz (Linux consolefonts)
)"},
    {8*256+14, R"(
* VGA ROM BIOS font (codepage 437)
* DISPLAY.SYS codepage 850
* DISPLAY.SYS codepage 852
* iso01.f14.psf.gz, is07.f14.psf.gz, iso14.f14.psf.gz (Linux consolefonts)
* lat1-14.psf.gz, lat2-14.psf.gz (Linux consolefonts)
* Uni1-VGA14.psf.gz, Uni2-VGA14.psf.gz, Uni3-TerminusBoldVGA14.psf.gz (Linux consolefonts)
)"},
    {8*256+15, R"(
* 8x15 source unknown (possibly created automatically by resizing 8x16)
)"},
    {8*256+16, R"(
* VGA ROM BIOS font (codepage 437)
* DISPLAY.SYS codepage 850
* DISPLAY.SYS codepage 852
* iso01.f16.psf.gz, is07.f16.psf.gz, iso16.f16.psf.gz (Linux consolefonts)
* lat1-16.psf.gz, lat2-16.psf.gz (Linux consolefonts)
* Uni1-VGA16.psf.gz, Uni2-VGA16.psf.gz, Uni3-TerminusBoldVGA16.psf.gz (Linux consolefonts)
* Arabic-VGA16.psf.gz, Hebrew-VGA16.psf.gz, FullCyrSlav-VGA16.psf.gz (Linux consolefonts)
* X11 Unifont `-gnu-unifont csur-medium-r-normal-sans-16-160-75-75-c-80-iso10646-1`, 8-pixel wide glyphs only

Pairs perfectly with 16x16.
)"},

    {11*256+22, R"(
* Uni2-TerminusBold22x11.psf.gz, Uni3-TerminusBold22x11.psf.gz (Linux consolefonts)
* FullCyrSlav-TerminusBold22x11.psf.gz, FullCyrAsia-TerminusBold22x11.psf.gz (Linux consolefonts)
* FullGreek-TerminusBold22x11.psf.gz (Linux consolefonts)
)"},
    {12*256+24, R"(
* Uni2-TerminusBold24x12.psf.gz, Uni3-TerminusBold24x12.psf.gz (Linux consolefonts)
* FullCyrSlav-TerminusBold24x12.psf.gz, FullCyrAsia-TerminusBold24x12.psf.gz (Linux consolefonts)
* FullGreek-TerminusBold24x12.psf.gz (Linux consolefonts)
)"},
    {14*256+28, R"(
* Uni2-TerminusBold28x14.psf.gz, Uni3-TerminusBold28x14.psf.gz (Linux consolefonts)
* FullCyrSlav-TerminusBold28x14.psf.gz, FullCyrAsia-TerminusBold28x14.psf.gz (Linux consolefonts)
* FullGreek-TerminusBold28x14.psf.gz (Linux consolefonts)
)"},
    {16*256+16, R"(
* X11 Unifont `-gnu-unifont csur-medium-r-normal-sans-16-160-75-75-c-80-iso10646-1`, 16-pixel wide glyphs only
)"},
    {16*256+28, R"(
* Uni1-VGA28x16.psf.gz, Uni2-VGA28x16.psf.gz (Linux consolefonts)
* FullCyrSlav-VGA28x16.psf.gz, FullGreek-VGA28x16.psf.gz (Linux consolefonts)
)"},
    {16*256+32, R"(
* Uni1-VGA32x16.psf.gz, Uni2-VGA32x16.psf.gz (Linux consolefonts)
* FullCyrSlav-VGA32x16.psf.gz (Linux consolefonts)
* Arabic-VGA32x16.psf.gz, Hebrew-VGA32x16.psf.gz (Linux consolefonts)
)"},
